### ISSUE TITLE
[feature request] Remove/Delete mod from config

### ISSUE THREAD

**Issue by Jeebeevee** [meza/minecraft-mod-manager#212] opened 2023-01-25 12:58 UTC
Beside of the 'add', 'update' and 'list' function it would be nice to have a 'delete' or 'remove' function.
this one can remove a mod from the config bij entering the name or mod id.
on beside of that it would me good to have the mod id on the list from the list function.

I know it is now be done by edit the config files. but it would be nice to do it by the command line

**Comment by meza** [comment] 2023-01-25 13:37
Hey, thanks for this!

The remove feature is coming in the next update! You can follow along with this ticket: #50

**Comment by meza** [comment] 2023-01-26 13:09
closing this as a duplicate of #50

**Closed by meza** 2023-01-26 13:09 UTC
